settings:
  title: '状态监控'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: Ethan-J_Monkey1.jpeg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api-zheyu-ink
    name: api.zheyu.ink
    description: 'A new-api site.'
    url: 'https://api.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: open-zheyu-ink
    name: open.zheyu.ink
    description: 'A Open-WebUI site.'
    url: 'https://open.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: chat-zheyu-ink
    name: chat.zheyu.ink
    description: 'A NextChat site.'
    url: 'https://chat.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: lobe-zheyu-ink
    name: lobe.zheyu.ink
    description: 'Lobe Chat website'
    url: 'https://lobe.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: word-zheyu-one
    name: word.zheyu.ink
    description: '汉语新解'
    url: 'https://word.zheyu.ink'
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: count-zheyu-one
    name: count.zheyu.one
    description: 'Some proxies url'
    url: 'https://count.zheyu.one/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: count-zheyu-ink
    name: count.zheyu.ink
    description: 'Some proxies url'
    url: 'https://count.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: alist-zheyu-ink
    name: alist.zheyu.ink
    description: 'Alist'
    url: 'https://alist.zheyu.ink' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: texas-zheyu-ink
    name: texas.zheyu.ink
    description: "a Texas Hold'em game"
    url: 'https://texas.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: topo-zheyu-ink
    name: topo.zheyu.ink
    description: 'A Mesh Topology Generation Algorithm Demo'
    url: 'https://topo.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: www-zheyu-ink
    name: www.zheyu.ink
    description: 'Blog'
    url: 'https://www.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: pdf2zh-zheyu-ink
    name: pdf2zh.zheyu.ink
    description: 'PDF Translation'
    url: 'https://pdf2zh.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: vnt-zheyu-ink
    name: vnt.zheyu.ink
    description: 'vnt relay server management web'
    url: 'https://vnt.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: search-zheyu-ink
    name: search.zheyu.ink
    description: 'Searxng search engine'
    url: 'https://search.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: flyshadow-zheyu-ink
    name: flyshadow.zheyu.ink
    description: 'flyshadow management web'
    url: 'https://flyshadow.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: qyb-zheyu-ink
    name: qyb.zheyu.ink
    description: '家庭货币'
    url: 'https://qyb.zheyu.ink/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
